apiVersion: v1
data:
  sync_with_s3.py: |
    # Copyright 2020-2021 The Kubeflow Authors
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #      http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.

    from http.server import BaseHTTPRequestHandler, HTTPServer
    import json
    import os
    import base64

    kfp_version = os.environ["KFP_VERSION"]
    disable_istio_sidecar = os.environ.get("DISABLE_ISTIO_SIDECAR") == "true"
    secret_name_s3_accesskey = os.environ.get("SECRET_NAME_S3_ACCESSKEY")
    secret_name_s3_secretkey = os.environ.get("SECRET_NAME_S3_SECRETKEY")
    external_secret_role_arn = os.environ.get("EXTERNAL_SECRET_ROLE_ARN")


    class Controller(BaseHTTPRequestHandler):
        def sync(self, parent, children):
            pipeline_enabled = (
                parent.get("metadata", {})
                .get("labels", {})
                .get("pipelines.kubeflow.org/enabled")
            )

            if pipeline_enabled != "true":
                return {"status": {}, "children": []}

            # Compute status based on observed state.
            desired_status = {
                "kubeflow-pipelines-ready": len(children["Secret.v1"]) == 1
                and len(children["ConfigMap.v1"]) == 1
                and len(children["Deployment.apps/v1"]) == 2
                and len(children["Service.v1"]) == 2
                and len(children["DestinationRule.networking.istio.io/v1alpha3"]) == 1
                and len(children["AuthorizationPolicy.security.istio.io/v1beta1"]) == 1
                and "True"
                or "False"
            }

            # Generate the desired child object(s).
            # parent is a namespace
            namespace = parent.get("metadata", {}).get("name")
            desired_resources = [
                {
                    "apiVersion": "v1",
                    "kind": "ConfigMap",
                    "metadata": {
                        "name": "metadata-grpc-configmap",
                        "namespace": namespace,
                    },
                    "data": {
                        "METADATA_GRPC_SERVICE_HOST": "metadata-grpc-service.kubeflow",
                        "METADATA_GRPC_SERVICE_PORT": "8080",
                    },
                },
                # Visualization server related manifests below
                {
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "metadata": {
                        "labels": {"app": "ml-pipeline-visualizationserver"},
                        "name": "ml-pipeline-visualizationserver",
                        "namespace": namespace,
                    },
                    "spec": {
                        "selector": {
                            "matchLabels": {"app": "ml-pipeline-visualizationserver"},
                        },
                        "template": {
                            "metadata": {
                                "labels": {"app": "ml-pipeline-visualizationserver"},
                                "annotations": disable_istio_sidecar
                                and {"sidecar.istio.io/inject": "false"}
                                or {},
                            },
                            "spec": {
                                "containers": [
                                    {
                                        "image": "gcr.io/ml-pipeline/visualization-server:"
                                        + kfp_version,
                                        "imagePullPolicy": "IfNotPresent",
                                        "name": "ml-pipeline-visualizationserver",
                                        "ports": [{"containerPort": 8888}],
                                        "resources": {
                                            "requests": {"cpu": "50m", "memory": "200Mi"},
                                            "limits": {"cpu": "500m", "memory": "1Gi"},
                                        },
                                    }
                                ],
                                "serviceAccountName": "default-editor",
                            },
                        },
                    },
                },
                {
                    "apiVersion": "networking.istio.io/v1alpha3",
                    "kind": "DestinationRule",
                    "metadata": {
                        "name": "ml-pipeline-visualizationserver",
                        "namespace": namespace,
                    },
                    "spec": {
                        "host": "ml-pipeline-visualizationserver",
                        "trafficPolicy": {"tls": {"mode": "ISTIO_MUTUAL"}},
                    },
                },
                {
                    "apiVersion": "security.istio.io/v1beta1",
                    "kind": "AuthorizationPolicy",
                    "metadata": {
                        "name": "ml-pipeline-visualizationserver",
                        "namespace": namespace,
                    },
                    "spec": {
                        "selector": {
                            "matchLabels": {"app": "ml-pipeline-visualizationserver"}
                        },
                        "rules": [
                            {
                                "from": [
                                    {
                                        "source": {
                                            "principals": [
                                                "cluster.local/ns/kubeflow/sa/ml-pipeline"
                                            ]
                                        }
                                    }
                                ]
                            }
                        ],
                    },
                },
                {
                    "apiVersion": "v1",
                    "kind": "Service",
                    "metadata": {
                        "name": "ml-pipeline-visualizationserver",
                        "namespace": namespace,
                    },
                    "spec": {
                        "ports": [
                            {
                                "name": "http",
                                "port": 8888,
                                "protocol": "TCP",
                                "targetPort": 8888,
                            }
                        ],
                        "selector": {
                            "app": "ml-pipeline-visualizationserver",
                        },
                    },
                },
                # Artifact fetcher related resources below.
                {
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "metadata": {
                        "labels": {"app": "ml-pipeline-ui-artifact"},
                        "name": "ml-pipeline-ui-artifact",
                        "namespace": namespace,
                    },
                    "spec": {
                        "selector": {"matchLabels": {"app": "ml-pipeline-ui-artifact"}},
                        "template": {
                            "metadata": {
                                "labels": {"app": "ml-pipeline-ui-artifact"},
                                "annotations": disable_istio_sidecar
                                and {"sidecar.istio.io/inject": "false"}
                                or {},
                            },
                            "spec": {
                                "containers": [
                                    {
                                        "name": "ml-pipeline-ui-artifact",
                                        "image": "gcr.io/ml-pipeline/frontend:"
                                        + kfp_version,
                                        "imagePullPolicy": "IfNotPresent",
                                        "ports": [{"containerPort": 3000}],
                                        "resources": {
                                            "requests": {"cpu": "10m", "memory": "70Mi"},
                                            "limits": {"cpu": "100m", "memory": "500Mi"},
                                        },
                                    }
                                ],
                                "serviceAccountName": "default-editor",
                            },
                        },
                    },
                },
                {
                    "apiVersion": "v1",
                    "kind": "Service",
                    "metadata": {
                        "name": "ml-pipeline-ui-artifact",
                        "namespace": namespace,
                        "labels": {"app": "ml-pipeline-ui-artifact"},
                    },
                    "spec": {
                        "ports": [
                            {
                                "name": "http",  # name is required to let istio understand request protocol
                                "port": 80,
                                "protocol": "TCP",
                                "targetPort": 3000,
                            }
                        ],
                        "selector": {"app": "ml-pipeline-ui-artifact"},
                    },
                },
                {
                    "apiVersion": "kubernetes-client.io/v1",
                    "kind": "ExternalSecret",
                    "metadata": {
                        "name": "pipelines-s3-secret",
                        "namespace": namespace,
                    },
                    "spec": {
                        "backendType": "secretsManager",
                        "roleArn": external_secret_role_arn,
                        "data": [
                            {
                                "key": secret_name_s3_accesskey,
                                "name": "S3_ACCESSKEY",
                            },
                            {
                                "key": secret_name_s3_secretkey,
                                "name": "S3_SECRETKEY",
                            },
                        ],
                    },
                },
            ]
            print("Received request:", parent)
            print("Desired resources except secrets:", desired_resources)
            # Moved after the print argument because this is sensitive data.

            return {"status": desired_status, "children": desired_resources}

        def do_POST(self):
            # Serve the sync() function as a JSON webhook.
            observed = json.loads(self.rfile.read(int(self.headers.get("content-length"))))
            desired = self.sync(observed["parent"], observed["children"])

            self.send_response(200)
            self.send_header("Content-type", "application/json")
            self.end_headers()
            self.wfile.write(bytes(json.dumps(desired), "utf-8"))


    HTTPServer(("", 8080), Controller).serve_forever()
kind: ConfigMap
metadata:
  labels:
    app: kubeflow-pipelines-profile-controller
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  name: kubeflow-pipelines-profile-controller-code-dtk74624bc
  namespace: kubeflow
---
apiVersion: v1
data:
  DISABLE_ISTIO_SIDECAR: "false"
kind: ConfigMap
metadata:
  labels:
    app: kubeflow-pipelines-profile-controller
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  name: kubeflow-pipelines-profile-controller-env-5252m69c4c
  namespace: kubeflow
---
apiVersion: v1
data:
  METADATA_GRPC_SERVICE_HOST: metadata-grpc-service
  METADATA_GRPC_SERVICE_PORT: "8080"
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
    component: metadata-grpc-server
  name: metadata-grpc-configmap
  namespace: kubeflow
---
apiVersion: v1
data:
  config.json: |
    {
      "DBConfig": {
        "Host": "<<__rds.host__>>",
        "Port": <<__rds.port__>>,
        "DriverName": "mysql",
        "DataSourceName": "",
        "DBName": "<<__rds.db_name.pipelines__>>",
        "GroupConcatMaxLen": "4194304",
        "ConMaxLifeTimeSec": "120"
      },
      "ObjectStoreConfig": {
        "Host": "s3.amazonaws.com",
        "Region": "<<__aws_region__>>",
        "Secure": true,
        "BucketName": "<<__s3.bucket.pipelines__>>",
        "PipelineFolder": "<<__s3.path.pipelines__>>",
        "PipelinePath": "<<__s3.path.pipelines__>>",
        "AccessKey": "",
        "SecretAccessKey": ""
      },
      "InitConnectionTimeout": "6m",
      "DefaultPipelineRunnerServiceAccount": "pipeline-runner"
    }
  sample_config.json: |
    [
      {
        "name": "[Demo] XGBoost - Iterative model training",
        "description": "[source code](https://github.com/kubeflow/pipelines/blob/master/samples/core/train_until_good/train_until_good.py) This sample demonstrates iterative training using a train-eval-check recursive loop. The main pipeline trains the initial model and then gradually trains the model some more until the model evaluation metrics are good enough.",
        "file": "/samples/core/train_until_good/train_until_good.py.yaml"
      },
      {
        "name": "[Demo] TFX - Taxi tip prediction model trainer",
        "description": "[source code](https://github.com/kubeflow/pipelines/tree/master/samples/core/parameterized_tfx_oss) [GCP Permission requirements](https://github.com/kubeflow/pipelines/blob/master/samples/core/parameterized_tfx_oss#permission). Example pipeline that does classification with model analysis based on a public tax cab dataset.",
        "file": "/samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py.yaml"
      },
      {
        "name": "[Tutorial] Data passing in python components",
        "description": "[source code](https://github.com/kubeflow/pipelines/tree/master/samples/tutorials/Data%20passing%20in%20python%20components) Shows how to pass data between python components.",
        "file": "/samples/tutorials/Data passing in python components/Data passing in python components - Files.py.yaml"
      },
      {
        "name": "[Tutorial] DSL - Control structures",
        "description": "[source code](https://github.com/kubeflow/pipelines/tree/master/samples/tutorials/DSL%20-%20Control%20structures) Shows how to use conditional execution and exit handlers. This pipeline will randomly fail to demonstrate that the exit handler gets executed even in case of failure.",
        "file": "/samples/tutorials/DSL - Control structures/DSL - Control structures.py.yaml"
      }
    ]
kind: ConfigMap
metadata:
  labels:
    app: ml-pipeline
  name: ml-pipeline-config
  namespace: kubeflow
---
apiVersion: v1
data:
  viewer-pod-template.json: |-
    {
        "spec": {
            "serviceAccountName": "default-editor"
        }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-ui-configmap
  namespace: kubeflow
---
apiVersion: v1
data:
  viewer-tensorboard-template.json: |
    {
        "spec": {
            "containers": [
                {
                    "env": [
                        {
                            "name": "AWS_ACCESS_KEY_ID",
                            "valueFrom": {
                                "secretKeyRef": {
                                    "name": "pipelines-s3-secret",
                                    "key": "S3_ACCESSKEY"
                                }
                            }
                        },
                        {
                            "name": "AWS_SECRET_ACCESS_KEY",
                            "valueFrom": {
                                "secretKeyRef": {
                                    "name": "pipelines-s3-secret",
                                    "key": "S3_SECRETKEY"
                                }
                            }
                        },
                        {
                            "name": "AWS_REGION",
                            "value": "<<__aws_region__>>"
                        }
                    ]
                }
            ]
        }
    }
kind: ConfigMap
metadata:
  name: ml-pipeline-ui-viewer-template
  namespace: kubeflow
---
apiVersion: v1
data:
  DEFAULTPIPELINERUNNERSERVICEACCOUNT: default-editor
  MULTIUSER: "true"
  VISUALIZATIONSERVICE_NAME: ml-pipeline-visualizationserver
  VISUALIZATIONSERVICE_PORT: "8888"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  name: pipeline-api-server-config-dc9hkg52h6
  namespace: kubeflow
---
apiVersion: v1
data:
  ConMaxLifeTimeSec: "120"
  appName: pipeline
  appVersion: 1.6.0
  autoUpdatePipelineDefaultVersion: "true"
  bucketName: mlpipeline
  cacheDb: cachedb
  cacheImage: gcr.io/google-containers/busybox
  cacheNodeRestrictions: "false"
  cronScheduleTimezone: UTC
  dbHost: mysql
  dbPort: "3306"
  mlmdDb: metadb
  pipelineDb: mlpipeline
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  name: pipeline-install-config
  namespace: kubeflow
---
apiVersion: v1
data:
  DB_NAME_CACHE: <<__rds.db_name.cache__>>
  DB_NAME_METADATA: <<__rds.db_name.metadata__>>
  DB_NAME_PIPELINES: <<__rds.db_name.pipelines__>>
  RDS_HOST: <<__rds.host__>>
  RDS_PORT: <<__rds.port__>>
kind: ConfigMap
metadata:
  name: pipelines-rds-config
  namespace: kubeflow
---
apiVersion: v1
data:
  BUCKET_NAME: <<__s3.bucket.pipelines__>>
  PIPELINE_FOLDER: <<__s3.path.pipelines__>>
  PIPELINE_PATH: <<__s3.path.pipelines__>>
  REGION: <<__aws_region__>>
kind: ConfigMap
metadata:
  name: pipelines-s3-config
  namespace: kubeflow
---
apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: <<__s3.bucket.pipelines__>>
      keyPrefix: <<__s3.key_prefix.pipelines__>>
      endpoint: s3.amazonaws.com
      region: <<__aws_region__>>
      insecure: false
      accessKeySecret:
        name: pipelines-s3-secret
        key: S3_ACCESSKEY
      secretKeySecret:
        name: pipelines-s3-secret
        key: S3_SECRETKEY
  containerRuntimeExecutor: pns
  executor: |
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 0.01
        memory: 32Mi
      limits:
        cpu: 0.5
        memory: 512Mi
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller-configmap
  namespace: kubeflow
