apiVersion: v1
kind: Service
metadata:
  name: {{ include "katib.fullname" . }}-controller
  namespace: kubeflow
  labels:
    {{- include "katib.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: {{ .Values.controller.service.metrics.port | quote }}
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.controller.service.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: http-webhook
    - port: {{ .Values.controller.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "katib.controllerSelectorLabels" . | nindent 4 }}
