apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: mysql-percona-allow-all
  namespace: kubeflow
  labels: {{- include "mysql-cluster.labels" . | nindent 4 }}
  # annotations:
  #   helm.sh/hook: post-install
  #   helm.sh/hook-weight: "5"
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/name: percona-xtradb-cluster
  rules:
  - {}
