apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "mysql-cluster.fullname" . }}-bootstrap
  namespace: kubeflow
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
  labels: {{- include "mysql-cluster.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: percona-xtradb-cluster
  mtls:
    mode: DISABLE
