apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secrets
  namespace: kubeflow
type: Opaque
data:
  root: {{ .Values.secrets.root | b64enc | quote }}
  xtrabackup: {{ .Values.secrets.xtrabackup | b64enc | quote }}
  monitor: {{ .Values.secrets.monitor | b64enc | quote }}
  clustercheck: {{ .Values.secrets.clustercheck | b64enc | quote }}
  proxyadmin: {{ .Values.secrets.proxyadmin | b64enc | quote }}
  pmmserver: {{ .Values.secrets.pmmserver | b64enc | quote }}
  operator: {{ .Values.secrets.operator | b64enc | quote }}
  replication: {{ .Values.secrets.replication | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-db-user
  namespace: kubeflow
type: Opaque
data:
  USERNAME: {{ .Values.secrets.kubeflow_user | b64enc | quote }}
  PASSWORD: {{ .Values.secrets.kubeflow_password | b64enc | quote }}
