apiVersion: v1
data:
  namespace-labels.yaml: |
    # Below is a list of labels to be set by default.
    #
    # To add a namespace label, use `key: 'value'`, for example:
    # istio.io/rev: 'asm-191-1'
    #
    # To remove a namespace label, use `key: ''`. For example:
    # istio-injection: ''
    #
    # Profile controller will not replace a namespace label if its key already
    # exists. If you want to override the value of a previously applied label, you
    # need to:
    # 1. Remove the label by using `key: ''` and deploy.
    # 2. Add the label by using `key: 'value'` and deploy.
    #
    {{- toYaml .Values.config.namespaceLables | nindent 4 }}
kind: ConfigMap
metadata:
  labels:
    kustomize.component: profiles
  name: {{ include "profile-controller.fullname" . }}-namespace-labels-data
  namespace: kubeflow
---
apiVersion: v1
data:
  ADMIN: {{ .Values.config.adminUserEmail }}
  USERID_HEADER: {{ .Values.global.userIDHeader }}
  USERID_PREFIX: {{ .Values.global.userIDPrefix | quote }}
  ISSUER: {{ .Values.global.oidcIssuer }}
  JWKSURI: {{ .Values.global.jwksURI }}
  WORKLOAD_IDENTITY: ""
  DEFAULTNAMESPACELABELSPATH: /etc/profile-controller/namespace-labels.yaml
kind: ConfigMap
metadata:
  labels: {{- include "profile-controller.labels" . | nindent 4 }}
  name: {{ include "profile-controller.fullname" . }}-config
  namespace: kubeflow
---
apiVersion: v1
data:
  network-policy.yaml: |-
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: kubeflow-default-ingress-egress
      namespace: {{ .Namespace }}
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
      - Egress
      ingress:
      - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              istio: system
        - namespaceSelector:
            matchLabels:
              app.plural.sh/name: monitoring
          podSelector:
            matchLabels:
              app: prometheus
        - namespaceSelector:
            matchLabels:
              app.plural.sh/name: kubeflow
          podSelector:
            matchLabels:
              app: notebooks-controller
        - namespaceSelector:
            matchLabels:
              app.plural.sh/name: knative
      egress:
      - to:
        - podSelector: {}
      - to:
        - namespaceSelector:
            matchLabels:
              kube-system: "true"
        ports:
        - protocol: UDP
          port: 53
      - to:
        - namespaceSelector:
            matchLabels:
              istio: system
      - to:
        - namespaceSelector:
            matchLabels:
              app.plural.sh/name: kubeflow
  test-template.yaml: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-template-configmap
      namespace: {{ .Namespace }}
    data:
      number: "{{ .Count }}"
      items-are-made-of: {{ .Material }}
  kfp.yaml: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: metadata-grpc-configmap
      namespace: {{ .Namespace }}
    data:
      METADATA_GRPC_SERVICE_HOST: "kubeflow-pipelines-metadata-grpc-server.kubeflow"
      METADATA_GRPC_SERVICE_PORT: "8080"
    ---
    # Visualization server related manifests below
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ml-pipeline-visualizationserver
      name: ml-pipeline-visualizationserver
      namespace: {{ .Namespace }}
    spec:
      selector:
        matchLabels:
          app: ml-pipeline-visualizationserver
      template:
        metadata:
          labels:
            app: ml-pipeline-visualizationserver
          annotations: {}
        spec:
          containers:
          - name: ml-pipeline-visualizationserver
            image: gcr.io/ml-pipeline/visualization-server:1.6.0
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 8888
            resources:
              requests:
                cpu: 50m
                memory: 200Mi
              limits:
                cpu: 500m
                memory: 1Gi
          serviceAccountName: default-editor
    ---
    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: ml-pipeline-visualizationserver
      namespace: {{ .Namespace }}
    spec:
      host: ml-pipeline-visualizationserver
      trafficPolicy:
        tls:
          mode: ISTIO_MUTUAL
    ---
    apiVersion: security.istio.io/v1beta1
    kind: AuthorizationPolicy
    metadata:
      name: ml-pipeline-visualizationserver
      namespace: {{ .Namespace }}
    spec:
      selector:
        matchLabels:
          app: ml-pipeline-visualizationserver
      rules:
      - from:
        - source:
            principals:
            - cluster.local/ns/kubeflow/sa/kubeflow-pipelines-api-server
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: ml-pipeline-visualizationserver
      namespace: {{ .Namespace }}
    spec:
      selector:
        app: ml-pipeline-visualizationserver
      ports:
      - name: http
        port: 8888
        protocol: TCP
        targetPort: 8888
    ---
    # Artifact fetcher related resources below.
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ml-pipeline-ui-artifact
      name: ml-pipeline-ui-artifact
      namespace: {{ .Namespace }}
    spec:
      selector:
        matchLabels:
          app: ml-pipeline-ui-artifact
      template:
        metadata:
          labels:
            app: ml-pipeline-ui-artifact
          annotations: {}
        spec:
          containers:
          - name: ml-pipeline-ui-artifact
            image: gcr.io/ml-pipeline/frontend:1.6.0
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 3000
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: S3_ACCESSKEY
                  name: pipelines-s3-secret
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: S3_SECRETKEY
                  name: pipelines-s3-secret
            resources:
              requests:
                cpu: 10m
                memory: 70Mi
              limits:
                cpu: 100m
                memory: 500Mi
          serviceAccountName: default-editor
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: ml-pipeline-ui-artifact
      namespace: {{ .Namespace }}
      labels:
        app: ml-pipeline-ui-artifact
    spec:
      selector:
        app: ml-pipeline-ui-artifact
      ports:
      - name: http  # name is required to let istio understand request protocol
        port: 80
        protocol: TCP
        targetPort: 3000
kind: ConfigMap
metadata:
  labels: {{- include "profile-controller.labels" . | nindent 4 }}
  name: {{ include "profile-controller.fullname" . }}-templates
  namespace: kubeflow
