apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-grpc-configmap
  labels:
    component: metadata-grpc-server
data:
  METADATA_GRPC_SERVICE_HOST: {{ include "pipelines.fullname" . }}-metadata-grpc-server
  METADATA_GRPC_SERVICE_PORT: {{ .Values.metadata.grpc.service.port | quote }}
